version: 2
jobs:
  build-ausgov:
    docker:
      - image: circleci/node:8.11.3 # NodeLTS as of 06/2018
    environment:
      NODE_ENV: "production" # Won't install anything from devDependencies.
    steps:
      - checkout
      - run: 
          name: Remove conflicting cache dirs, if any
          command: rm -rf .cache && rm -rf node_modules
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - m5-yarn-packages-{{ checksum "package.json" }}-lock-{{ checksum "yarn.lock" }}
      - run: 
          name: Install dependencies
          command: yarn install --check-files --cache-folder ~/.cache
      - save_cache:
          name: Save Yarn Package Cache
          key: m5-yarn-packages-{{ checksum "package.json" }}-lock-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - .cache #yarn cache is empty
      - run: 
          name: Build alpha.australia.gov.au
          command: yarn run build
      - persist_to_workspace:
          root: ~/project # /home/circleci/project
          paths:
            - ./deploy
            - ./public
  deploy-stag:
    docker:
      - image: govau/cf-cli
    steps:
      - attach_workspace:
          at: ~/project # /home/root/project
      - run:
          name: Deploying to cloud.gov.au
          command: |
            cf login -a api.system.y.cld.gov.au -o dta -s $CF_STAG_SPACE -u $CF_STAG_USER -p $CF_STAG_PASS
            cf zero-downtime-push ausgov1 -f ./deploy/stag-manifest.yml
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-ausgov:
          filters:
            branches:
              only:
                - issue/34-Resolve-circleci-asset-cache # Testing
      - deploy-stag:
          requires:
            - build-ausgov